/**
 * Runtime for the auto-converted eQUILIBRIUM drawings (views generated by
 * tools/convert.py from the view_N_compas.py GeoGebra dumps).
 *
 * The converted view is a flat element list in GeoGebra construction order.
 * Consecutive elements of the same kind and color are grouped into ONE
 * construction step (all verticals together, all load arrows together, ...),
 * the StepPlayer walks through the groups, the group being drawn is pink, and
 * everything stays visible once drawn -- the drawing only ever accumulates.
 *
 * Element encodings (produced by the converter):
 *   ['p', x, y, label, style]      point: style 'w' = white handle, 'g' = derived
 *   ['s', [x0,y0,x1,y1], hex, px]  segment
 *   ['a', [x0,y0,x1,y1], hex, px]  vector (tail->tip); filled triangular head
 *   ['l', [[x,y], ...], hex, px]   polyline
 *   ['g', [[x,y], ...], hex, op]   filled region (rendered very subtly)
 *   ['c', [cx,cy,r], hex, px]      circle outline
 * Elements before meta.nFrame are the drawing frame: always visible, no step.
 */

import { PAL } from './eqdraw.js';
import { isFrameArt } from './stepview.js';

const COLOR_NAME = {
  0x51923D: 'load', 0xE07A26: 'force', 0x2563EB: 'compression',
  0xA52B30: 'tension', 0xA0A0A0: 'construction', 0x111111: 'structure',
};
const GREY = 0xA0A0A0;

function groupCaption(kind, color, count, labels) {
  if (kind === 'p') {
    const names = labels.slice(0, 5).join(', ') + (labels.length > 5 ? ', …' : '');
    return count === 1 ? [`Point ${names}`, 'place the point']
      : [`Points ${names}`, `place ${count} points`];
  }
  const name = COLOR_NAME[color] ?? 'drawing';
  const cap = name[0].toUpperCase() + name.slice(1);
  if (kind === 'a') {
    return count === 1 ? [`${cap} arrow`, `draw the ${name} arrow`]
      : [`${cap} arrows`, `draw ${count} ${name} arrows`];
  }
  if (kind === 'g') {
    return count === 1 ? ['Shaded region', 'shade the region']
      : ['Shaded regions', `shade ${count} regions`];
  }
  if (kind === 'c') {
    return count === 1 ? ['Circle', 'draw the circle'] : ['Circles', `draw ${count} circles`];
  }
  return count === 1 ? [`${cap} line`, `draw the ${name} line`]
    : [`${cap} lines`, `draw ${count} ${name} lines`];
}

export function createStatic(dw, panel, makePlayer, meta, elements) {
  // legacy dumps carry the old baked tension red; remap it to the palette,
  // and never draw the export-frame rectangle / ground line
  let nFrameAdj = meta.nFrame ?? 0;
  const kept = [];
  elements.forEach((el, i) => {
    el = el.map((v) => (v === 0xA52B30 ? PAL.red : v));
    const art = (el[0] === 's' && isFrameArt([[el[1][0], el[1][1]], [el[1][2], el[1][3]]], meta.frame))
      || (el[0] === 'l' && isFrameArt(el[1], meta.frame));
    if (art) {
      if (i < (meta.nFrame ?? 0)) nFrameAdj -= 1;
      return;
    }
    kept.push(el);
  });
  elements = kept;
  meta = { ...meta, nFrame: nFrameAdj };
  const W = meta.frame[1][0] - meta.frame[0][0];
  const thin = 0.0012 * W, thick = 0.0024 * W;
  const rHandle = 0.0035 * W, rDerived = 0.0022 * W;   // small points, as in the video
  const nFrame = meta.nFrame ?? 0;
  const width = (px) => (px >= 2.0 ? thick : thin);

  // ---- group consecutive same-kind / same-color elements into steps --------
  const groupKey = (el) => (el[0] === 'p' ? `p${el[4]}` : `${el[0]}:${el[2]}`);
  const steps = [
    { t: 'How to draw this scheme', d: 'step through with the slider, press play, or use ←/→' },
  ];
  const intros = [];
  let prevKey = null;
  let group = null;
  const pushGroup = () => {
    if (!group) return;
    const [t, d] = groupCaption(...group);
    steps.push({ t, d });
  };
  for (let i = 0; i < elements.length; i++) {
    if (i < nFrame) {
      intros.push(0);
      continue;
    }
    const el = elements[i];
    const key = groupKey(el);
    if (key !== prevKey) {
      pushGroup();
      group = [el[0], el[0] === 'p' ? 0 : el[2], 0, []];
      prevKey = key;
    }
    group[2] += 1;
    if (el[0] === 'p') group[3].push(el[3]);
    intros.push(steps.length);           // current group becomes step steps.length
  }
  pushGroup();
  steps.push({ t: 'Done', d: 'the complete drawing' });  // final step: nothing pink

  // ---- build the scene -----------------------------------------------------
  elements.forEach((el, i) => {
    const name = `e${i}`;
    const intro = intros[i];
    const z = 0.0008 * i;
    const [kind] = el;

    if (kind === 'p') {
      const derived = el[4] === 'g';
      dw.disk(name, {
        intro, z: 0.35 + 0.0002 * i,
        r: derived ? rDerived : rHandle,
        face: derived ? PAL.grey : PAL.white,
        edge: derived ? PAL.grey : PAL.black,
      });
      dw.setDisk(name, [el[1], el[2]]);
      if (el[3]) {
        dw.label(`${name}t`, el[3], { cls: 'point', intro });
        dw.setLabel(`${name}t`, [el[1] + 0.008 * W, el[2] + 0.007 * W]);
      }
    } else if (kind === 's') {
      if (el[2] === GREY) {                        // guides / temporary lines: dashed
        dw.dashLine(name, { intro, z, dash: 0.008 * W });
        dw.setDashLine(name, [[el[1][0], el[1][1]], [el[1][2], el[1][3]]]);
      } else {
        dw.seg(name, { intro, z, w: width(el[3]), color: el[2] });
        dw.setSeg(name, [el[1][0], el[1][1]], [el[1][2], el[1][3]]);
      }
    } else if (kind === 'a') {
      dw.arrow(name, {
        intro, z: 0.1 + z, w: width(el[3]), color: el[2],
        headLen: 0.016 * W, headW: 0.006 * W,
      });
      dw.setArrow(name, [el[1][0], el[1][1]], [el[1][2], el[1][3]]);
    } else if (kind === 'l') {
      if (el[2] === GREY) {                        // guides / temporary lines: dashed
        dw.dashLine(name, { intro, z, dash: 0.008 * W });
        dw.setDashLine(name, el[1]);
      } else {
        dw.strokes(name, el[1].length - 1, { intro, z, w: width(el[3]), color: el[2] });
        const pairs = [];
        for (let j = 0; j < el[1].length - 1; j++) pairs.push([el[1][j], el[1][j + 1]]);
        dw.setStrokes(name, pairs);
      }
    } else if (kind === 'c') {
      dw.circle(name, { intro, z, color: el[2] });
      dw.setCircle(name, [el[1][0], el[1][1]], el[1][2]);
    }
  });

  const player = makePlayer(steps, () => player.apply({}, {}));

  const view = panel.section('View');
  panel.button(view, 'zoom fit', () => dw.zoomFit());

  player.set(player.k);
  return player;
}
